---

- name: Set RHEL Cert Repos
  shell: subscription-manager repos --enable=rhel-7-server-cert-rpms --enable=rhel-7-server-openstack-7.0-rpms

- name: remove the openstack-dashboard
  yum: name=openstack-dashboard state=absent

- name: remove horizon_vhost.conf
  file: path=/etc/httpd/conf.d/10-horizon_vhost.conf state=absent
  register: horizon_vhost_removed

- name: restart httpd
  shell: "systemctl daemon-reload && systemctl restart httpd"
  when: horizon_vhost_removed.changed

- name: install certification rpms
  yum: name={{ item.name }}
  with_items:
    - { name: "redhat-certification" }
    - { name: "redhat-certification-openstack" }

- name: copy cert config
  shell: cp /etc/rhcert-default.xml /etc/rhcert.xml

- name: restart httpd (again)
  service: name=httpd state=reloaded

- name: test_config.json
  template: src=test_config.json dest=/etc/redhat-certification-openstack/test_config.json mode=644
