---

  - name: Determine if AdminRtr is already setup
    sudo_user: stack
    shell: >
      source /home/stack/overcloudrc &&
        neutron router-list --format csv --quote minimal | grep 'AdminRtr,' | sed 's_,.*__'
    register: test_router_id

  - name: Create new public network
    sudo_user: stack
    shell: >
      source /home/stack/overcloudrc &&
        neutron net-create public --router:external --provider:segmentation_id=1199 --provider:network_type=vlan --provider:physical_network datacentre
    when: test_router_id.stdout == ''

  - name: Create new subnet for the public network
    sudo_user: stack
    shell: >
      source /home/stack/overcloudrc &&
        neutron subnet-create --name public --allocation-pool start={{ overcloud_floating_ip_start }},end={{ overcloud_floating_ip_end }} public {{ overcloud_floating_ip_cidr }}
    when: test_router_id.stdout == ''

  - name: Create the AdminRtr
    sudo_user: stack
    shell: >
      source /home/stack/overcloudrc &&  neutron router-create AdminRtr
    when: test_router_id.stdout == ''


  - name: Set the AdminRtr gateway to use the public network
    sudo_user: stack
    shell: >
      source /home/stack/overcloudrc && neutron router-gateway-set AdminRtr public
    when: test_router_id.stdout == ''

