---

- name: Find Overcloud Connection Properties (OS_AUTH_URL)
  shell: "source /home/stack/overcloudrc && echo ${OS_AUTH_URL}"
  register: OS_AUTH_URL

- name: Find Overcloud Connection Properties (OS_PASSWORD)
  shell: "source /home/stack/overcloudrc && echo ${OS_PASSWORD}"
  register: OS_PASSWORD

- name: Set Overcloud Connection Variables
  set_fact:
    overcloud_os_auth_url: "{{ OS_AUTH_URL['stdout'] }}"
    overcloud_os_admin_password: "{{ OS_PASSWORD['stdout'] }}"

- name: Find Overcloud Controller Nodes
  sudo_user: stack
  shell: >
        source /home/stack/stackrc &&
        openstack server list
        --format csv
        --quote minimal
        -c Networks
        --name overcloud-controller |
        grep ctlplane | sed 's_.*\=__'
  register: overcloud_controller_ips

- name: Find Overcloud Compute Nodes
  sudo_user: stack
  shell: >
        source /home/stack/stackrc &&
        openstack server list
        --format csv
        --quote minimal
        -c Networks
        --name overcloud-compute |
        grep ctlplane | sed 's_.*\=__'
  register: overcloud_compute_ips

- name: Add Overcloud Controller hosts to 'overcloud_controller' group
  add_host:
    hostname: "{{ item }}"
    groups: overcloud_controller
  with_items: overcloud_controller_ips.stdout_lines

- name: Add Overcloud Compute hosts to 'overcloud_compute' group
  add_host:
    hostname: "{{ item }}"
    groups: overcloud_compute
  with_items: overcloud_compute_ips.stdout_lines

- name: Allow root ssh on Overcloud Contrller Nodes
  sudo_user: stack
  shell: >
         ssh  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
         heat-admin@{{ item }}
         sudo sed -i'' 's_.*ssh-rsa_ssh-rsa_' /root/.ssh/authorized_keys
  with_items: overcloud_controller_ips.stdout_lines

- name: Allow root ssh on Overcloud Compute Nodes
  sudo_user: stack
  shell: >
         ssh  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
         heat-admin@{{ item }}
         sudo sed -i'' 's_.*ssh-rsa_ssh-rsa_' /root/.ssh/authorized_keys
  with_items: overcloud_compute_ips.stdout_lines


- name: Build authorized keys file
  shell: "cat /root/.ssh/authorized_keys /home/stack/.ssh/id_rsa.pub > /tmp/authorized_keys"

- name: Set authorized_keys on Overcloud Controller Nodes
  shell: >
         scp -i /home/stack/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
         /tmp/authorized_keys
         root@{{ item }}:/root/.ssh/authorized_keys
  with_items: overcloud_controller_ips.stdout_lines

- name: Set authorized_keys on Overcloud Compute Nodes
  shell: >
        scp -i /home/stack/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
        /tmp/authorized_keys
        root@{{ item }}:/root/.ssh/authorized_keys
  with_items: overcloud_compute_ips.stdout_lines



# sysctl.d/99-bridge.conf is also needed on compute nodes
- name: Write sysctl.d/99-bridge.conf
  template: src=99-bridge.conf dest=/home/stack/99-bridge.conf mode=644

- name: Upload /etc/sysctl.d/99-bridge.conf to compute nodes
  shell: >
        scp -i /home/stack/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
        /home/stack/99-bridge.conf
        root@{{ item }}:/etc/sysctl.d/99-bridge.conf
  with_items: overcloud_compute_ips.stdout_lines

- name: Reload sysctl on remote compute
  shell: >
        ssh -i /home/stack/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
        root@{{ item }} sysctl --system
  with_items: overcloud_compute_ips.stdout_lines

- name: Bld the ansible inventory file for overcloud
  sudo_user: stack
  shell: source /home/stack/stackrc && . /home/stack/openstack-tools/openstack/tripleo_bld_ansible_inv.sh /home/stack/ansible_hosts

- name: install filebeat on the overcloud nodes
  sudo_user: stack
  shell: source /home/stack/venv_ansible/bin/activate && ansible-playbook -i /home/stack/ansible_hosts /home/stack/openstack-tools/openstack/ansible/setup_filebeat.yml -e "filebeat_port={{ filebeat_port }} testbed_name={{ testbed_name if testbed_name is defined else ansible_hostname }}"

