---

- name: Add Member Role to Keystone
  sudo_user: stack
  shell: source /home/stack/overcloudrc && keystone role-list | grep -q Member || keystone role-create --name=Member

- name: Setup Yum Repos
  environment: proxy_env
  get_url: url={{ item.url }} dest=/etc/yum.repos.d/{{ item.name }} force=true
  with_items: "{{ cert_yum_repos }}"

- name: Create dir for tempest.conf
  file: path=/etc/redhat-certification-openstack state=directory mode=0755

- name: install tempest rpms
  yum: name={{ item.name }}
  with_items:
    - { name: "openstack-tempest" }

- name: Write tempest.conf
  shell: >
        cd /usr/share/openstack-tempest-kilo &&
        python tools/config_tempest.py --image "http://download.cirros-cloud.net/0.3.3/cirros-0.3.3-x86_64-disk.img"
        --create identity.uri {{ hostvars[director_node_ssh_ip]['overcloud_os_auth_url'] }}
        identity.username demo
        identity.password demo
        identity.auth_version v2
        identity.tenant_name demo
        identity.admin_domain_name Default
        auth.allow_tenant_isolation True
        auth.tempest_roles _member_
        network.ipv6 false
        compute.build_timeout 500
        compute.ssh_timeout 500
        orchestration.build_timeout 50000
        network.ipv6_subnet_attributes false
        compute-feature-enabled.live_migration false
        identity.admin_username admin
        identity.admin_password {{ hostvars[director_node_ssh_ip]['overcloud_os_admin_password'] }}
        --out /etc/redhat-certification-openstack/tempest.conf

# Need this for tempest.api.orchestration.stacks.test_neutron_resources.NeutronResourcesTestJSON
- name: Create heat_stack_owner role
  sudo_user: stack
  shell: >
         source /home/stack/overcloudrc && openstack role list |
         grep -q heat_stack_owner || openstack role create heat_stack_owner

- name: Run quick network sanity test (tempest)
  shell: >
         cd /usr/share/openstack-tempest-kilo &&
         ./run_tempest.sh -N -- 'test_connectivity_between_vms_on_different_networks'
         --config /etc/redhat-certification-openstack/tempest.conf
  when: not run_long_tempest

- name: Run longer network tests (tempest)
  shell: >
        cd /usr/share/openstack-tempest-kilo &&
        cp /etc/redhat-certification-openstack/tempest.conf /usr/share/openstack-tempest-kilo/etc/tempest.conf &&
        sleep 60 &&
        ./run_tempest.sh -N --config /etc/redhat-certification-openstack/tempest.conf --serial network
#        testr run --parallel --concurrency 1 network
#        ./run_tempest.sh -N
#        --config /etc/redhat-certification-openstack/tempest.conf
#        --serial
#        tempest.api.network
#        tempest.scenario.test_load_balancer_basic
#        tempest.scenario.test_network_advanced_server_ops
#        tempest.scenario.test_network_basic_ops
#        tempest.scenario.test_security_groups_basic_op
#        tempest.scenario.test_network_v6
  async: 7200
  poll: 60
  when: run_long_tempest
  ignore_errors: yes