resource_registry:
  OS::TripleO::BlockStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/templates/nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/nic-configs/controller.yaml
  OS::TripleO::ObjectStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/swift-storage.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/ceph-storage.yaml

parameters:
  # Set to "br-ex" if using floating IPs on native VLAN on bridge br-ex
  Controller-1::NeutronExternalNetworkBridge: "''"

#parameter_defaults:
#  ExternalNetCidr: {{ overcloud_floating_ip_cidr }}
#  ExternalAllocationPools: [{'start': '{{ overcloud_floating_ip_start }}', 'end': '{{ overcloud_floating_ip_end }}'}]
#  ExternalNetworkVlanID: {{ overcloud_vlan }}
#  ExternalInterfaceDefaultRoute: {{ overcloud_bm_network_gateway }}

