---
- hosts: director
  vars:
    ansible_user: stack
  tasks:
    - name: Include tasks for OSP version
      include_tasks: "step4-update-undercloud-and-overcloud/{{ dci_topic | lower }}/tasks.yaml"
